<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>psdPH.Core.Compositons</RootNamespace>
    <AssemblyName>psdPH.Core.Compositons</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU</Platforms>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='NoViews|AnyCPU'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\psdPH.Core\psdPH.Parameters.csproj" />
    <ProjectReference Include="..\psdPH.Localization\psdPH.Localization.csproj" />
    <ProjectReference Include="..\psdPH.Nodes.Core\psdPH.Nodes.Core.csproj" />
    <ProjectReference Include="..\psdPH.Photoshop\psdPH.Photoshop.csproj" />
    <ProjectReference Include="..\psdPH.Serialization\psdPH.Serialization.csproj" />
    <ProjectReference Include="..\psdPH.Setups.Core\psdPH.Setups.Core.csproj" />
    <ProjectReference Include="..\psdPH.Setups\psdPH.Setups.csproj" />
    <ProjectReference Include="..\psdPH.Utils\psdPH.Utils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="Photoshop">
      <Guid>{E891EE9A-D0AE-4CB4-8871-F92C0109F18E}</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>False</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>