<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>psdPH.TemplateEditor</RootNamespace>
    <AssemblyName>psdPH.TemplateEditor</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU</Platforms>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='NoViews|AnyCPU'">
    <OutputPath>bin\NoViews\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>full</DebugType>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\psdPH.CED\psdPH.CED.csproj" />
    <ProjectReference Include="..\psdPH.Context\psdPH.Context.csproj" />
    <ProjectReference Include="..\psdPH.Core.Compositons\psdPH.Compositons.csproj" />
    <ProjectReference Include="..\psdPH.Core\psdPH.Parameters.csproj" />
    <ProjectReference Include="..\psdPH.Localization\psdPH.Localization.csproj" />
    <ProjectReference Include="..\psdPH.Nodes.Core\psdPH.Nodes.Core.csproj" />
    <ProjectReference Include="..\psdPH.Nodes.UI\psdPH.Nodes.UI.csproj" />
    <ProjectReference Include="..\psdPH.Nodes\psdPH.Nodes.csproj" />
    <ProjectReference Include="..\psdPH.Photoshop\psdPH.Photoshop.csproj" />
    <ProjectReference Include="..\psdPH.Project\psdPH.Project.csproj" />
    <ProjectReference Include="..\psdPH.Rules\psdPH.Rules.csproj" />
    <ProjectReference Include="..\psdPH.Serialization\psdPH.Serialization.csproj" />
    <ProjectReference Include="..\psdPH.Setups.Controls\psdPH.Setups.Controls.csproj" />
    <ProjectReference Include="..\psdPH.Setups.Core\psdPH.Setups.Core.csproj" />
    <ProjectReference Include="..\psdPH.Setups\psdPH.Setups.csproj" />
    <ProjectReference Include="..\psdPH.Utils\psdPH.Utils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="Photoshop">
      <Guid>{E891EE9A-D0AE-4CB4-8871-F92C0109F18E}</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>False</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <Compile Update="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
  </ItemGroup>

</Project>