<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    
    <RootNamespace>psdPH</RootNamespace>
    <AssemblyName>psdPH</AssemblyName>
    <Deterministic>true</Deterministic>
    
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.*</ApplicationVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <UseVSHostingProcess>true</UseVSHostingProcess>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'NoViews|AnyCPU'">
    <Prefer32Bit>true</Prefer32Bit>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="Photoshop">
      <Guid>{E891EE9A-D0AE-4CB4-8871-F92C0109F18E}</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
    <COMReference Include="PhotoshopTypeLibrary">
      <Guid>{4B0AB3E1-80F1-11CF-86B4-444553540000}</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <Lcid>1033</Lcid>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\psdPH.Photoshop\psdPH.Photoshop.csproj" />
    <ProjectReference Include="..\psdPH.Project\psdPH.Project.csproj" />
    <ProjectReference Include="..\psdPH.Serialization\psdPH.Serialization.csproj" />
    <ProjectReference Include="..\psdPH.Setups.Controls\psdPH.Setups.Controls.csproj" />
    <ProjectReference Include="..\psdPH.Setups.Core\psdPH.Setups.Core.csproj" />
    <ProjectReference Include="..\psdPH.Setups\psdPH.Setups.csproj" />
    <ProjectReference Include="..\psdPH.TemplateEditor\psdPH.TemplateEditor.csproj" />
    <ProjectReference Include="..\psdPH.Utils\psdPH.Utils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>