<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    
    <AssemblyName>test.TemplateEditor</AssemblyName>
    <RootNamespace>test.TemplateEditor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\psdPH.Core.Compositons\psdPH.Compositons.csproj" />
    <ProjectReference Include="..\psdPH.Photoshop\psdPH.Photoshop.csproj" />
    <ProjectReference Include="..\psdPH.Serialization\psdPH.Serialization.csproj" />
    <ProjectReference Include="..\psdPH.TemplateEditor\psdPH.TemplateEditor.csproj" />
    <ProjectReference Include="..\TestDefinitions\TestDefinitions.csproj" />
  </ItemGroup>

</Project>