using Microsoft.VisualStudio.TestTools.UnitTesting;
using Photoshop;
using psdPH;
using psdPH.Logic;
using psdPH.Logic.Compositions;
using psdPH.Logic.Rules;
using System;
using System.Collections.Generic;
using System.ComponentModel.Design;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Documents;
using System.Windows.Shapes;
using static psdPH.Logic.PhotoshopDocumentExtension;
using Application = Photoshop.Application;
using Microsoft.CSharp;
using System.Windows.Controls;
using psdPH.TemplateEditor.CompositionLeafEditor.Windows.Utils;
using psdPH.Photoshop;
using System.Windows.Controls.Primitives;
using System.Reflection;
using Condition = psdPH.Logic.Rules.Condition;
using System.Threading;
using HAli = System.Windows.HorizontalAlignment;
using VAli = System.Windows.VerticalAlignment;
using System.Threading.Tasks;
using psdPH.Views.WeekView;
using System.Xml.Serialization;
using psdPH.Views.WeekView.Logic;
using static psdPH.WeekConfig;
using psdPH.Utils;
using System.IO;
using System.Text;


